export interface Verse {
  id: string;
  number: string;
  speaker?: string;
  text: string;
}

export interface Chapter {
  id: number;
  title: string;
  verses: Verse[];
}

export const chapters: Chapter[] = [
  {
    id: 1,
    title: "Instruction on Self-Realization",
    verses: [
      { id: "1.1", number: "1.1", speaker: "Janaka said:", text: "Master,\nhow is Knowledge to be achieved,\ndetachment acquired,\nliberation attained?" },
      { id: "1.2", number: "1.2", speaker: "Ashtavakra said:", text: "To be free,\nshun the experiences of the senses\nlike poison.\nTurn your attention to\nforgiveness, sincerity, kindness, simplicity, truth." },
      { id: "1.3", number: "1.3", speaker: "Ashtavakra said:", text: "You are not earth, water, fire or air.\nNor are you empty space.\nLiberation is to know yourself\nas Awareness alone—\nthe Witness of these." },
      { id: "1.4", number: "1.4", speaker: "Ashtavakra said:", text: "Abide in Awareness\nwith no illusion of person.\nYou will be instantly free and at peace." },
      { id: "1.5", number: "1.5", speaker: "Ashtavakra said:", text: "You have no caste or duties.\nYou are invisible, unattached, formless.\nYou are the Witness of all things.\nBe happy." },
      { id: "1.6", number: "1.6", speaker: "Ashtavakra said:", text: "Right and wrong, pleasure and pain,\nexist in mind only.\nThey are not your concern.\nYou neither do nor enjoy.\nYou are free." },
      { id: "1.7", number: "1.7", speaker: "Ashtavakra said:", text: "You are the Solitary Witness\nof All That Is,\nforever free.\nYour only bondage is not seeing This." },
      { id: "1.8", number: "1.8", speaker: "Ashtavakra said:", text: "The thought: \"I am the doer\"\nis the bite of a poisonous snake.\nTo know: \"I do nothing\"\nis the wisdom of faith.\nBe happy." },
      { id: "1.9", number: "1.9", speaker: "Ashtavakra said:", text: "A single understanding:\n\"I am the One Awareness,\"\nconsumes all suffering\nin the fire of an instant.\nBe happy." },
      { id: "1.10", number: "1.10", speaker: "Ashtavakra said:", text: "You are unbounded Awareness—\nBliss, Supreme Bliss—\nin which the universe appears\nlike the mirage of a snake in a rope.\nBe happy." },
      { id: "1.11", number: "1.11", speaker: "Ashtavakra said:", text: "It is true what they say:\n\"You are what you think.\"\nIf you think you are bound you are bound.\nIf you think you are free you are free." },
      { id: "1.12", number: "1.12", speaker: "Ashtavakra said:", text: "You are Self—the Solitary Witness.\nYou are perfect, all-pervading, One.\nYou are free, desireless, forever still.\nThe universe is but a seeming in You." },
      { id: "1.13", number: "1.13", speaker: "Ashtavakra said:", text: "Meditate on this: \"I am Awareness alone—Unity itself.\"\nGive up the idea that you are separate, a person,\nthat there is within and without." },
      { id: "1.14", number: "1.14", speaker: "Ashtavakra said:", text: "You have long been bound thinking:\n\"I am a person.\"\nLet the knowledge: \"I am Awareness alone\"\nbe the sword that frees you." },
      { id: "1.15", number: "1.15", speaker: "Ashtavakra said:", text: "You are now and forever\nfree, luminous, transparent, still.\nThe practice of meditation\nkeeps one in bondage." },
      { id: "1.16", number: "1.16", speaker: "Ashtavakra said:", text: "You are pure Consciousness—\nthe substance of the universe.\nThe universe exists within you.\nDon't be small-minded." },
      { id: "1.17", number: "1.17", speaker: "Ashtavakra said:", text: "You are unconditioned, changeless, formless.\nYou are solid, unfathomable, cool.\nDesire nothing.\nYou are Consciousness." },
      { id: "1.18", number: "1.18", speaker: "Ashtavakra said:", text: "That which has form is not real.\nOnly the formless is permanent.\nOnce this is known,\nyou will not return to illusion." },
      { id: "1.19", number: "1.19", speaker: "Ashtavakra said:", text: "Just as a mirror exists\nboth within and without\nthe image reflected,\nthe Supreme Self exists\nboth within and without the body." },
      { id: "1.20", number: "1.20", speaker: "Ashtavakra said:", text: "Just as the same space exists\nboth within and without a jar,\nthe timeless, all-pervasive One\nexists as Totality." },
    ]
  },
  {
    id: 2,
    title: "Joy of Self-Realization",
    verses: [
      { id: "2.1", number: "2.1", speaker: "Janaka said:", text: "I am now spotless and at peace—\nAwareness beyond Consciousness.\nAll this time\nI have been duped by illusion." },
      { id: "2.2", number: "2.2", speaker: "Janaka said:", text: "By this light alone\nthe body and the universe appear.\nI am Everything\nor Nothing." },
      { id: "2.3", number: "2.3", speaker: "Janaka said:", text: "Seeing there is no\nuniverse or body,\nby grace the Self is revealed." },
      { id: "2.4", number: "2.4", speaker: "Janaka said:", text: "As waves, foam and bubbles\nare not different from water,\nso the universe emanating from Self\nis not different from Self." },
      { id: "2.5", number: "2.5", speaker: "Janaka said:", text: "Look closely at cloth,\nyou see only threads.\nLook closely at creation,\nyou see only Self." },
      { id: "2.6", number: "2.6", speaker: "Janaka said:", text: "As sweetness\npervades sugarcane juice,\nI am the essence of creation." },
      { id: "2.7", number: "2.7", speaker: "Janaka said:", text: "Not seeing Self, the world is materialized.\nSeeing Self, the world is vanished.\nA rope is not a snake,\nbut can appear to be." },
      { id: "2.8", number: "2.8", speaker: "Janaka said:", text: "I am not other than Light.\nThe universe manifests\nat my glance." },
      { id: "2.9", number: "2.9", speaker: "Janaka said:", text: "The mirage of universe appears in me\nas silver appears in mother-of-pearl,\nas a snake appears in a rope,\nas water appears on a desert horizon." },
      { id: "2.10", number: "2.10", speaker: "Janaka said:", text: "As a pot returns to clay,\na wave to water,\na bracelet to gold,\nso will the universe return to Me." },
      { id: "2.11", number: "2.11", speaker: "Janaka said:", text: "I am wonderful indeed—\nbeyond adoration.\nI cannot decay nor ever die,\nthough God and all the universe\nshould perish to the last blade of grass." },
      { id: "2.12", number: "2.12", speaker: "Janaka said:", text: "I am wonderful indeed—\nbeyond adoration.\nEven with a body I am One.\nI neither come nor go.\nI am everywhere at once." },
      { id: "2.13", number: "2.13", speaker: "Janaka said:", text: "I am wonderful indeed—\nbeyond adoration.\nI am astounded at my powers.\nThe universe appears within me\nbut I do not touch it." },
      { id: "2.14", number: "2.14", speaker: "Janaka said:", text: "I am wonderful indeed—\nbeyond adoration.\nI am everything thought or spoken,\nand have nothing." },
      { id: "2.15", number: "2.15", speaker: "Janaka said:", text: "In Reality,\nknowledge, the knower, and the knowable\ndo not exist.\nI am the transparent Self\nin which through ignorance\nthey appear." },
      { id: "2.16", number: "2.16", speaker: "Janaka said:", text: "Looking at One and seeing many\nis the cause of all misery.\nThe only cure is to realize\nwhat is seen is not there.\nI am One—aware, blissful, immaculate." },
      { id: "2.17", number: "2.17", speaker: "Janaka said:", text: "I am unbounded Awareness.\nOnly in imagination do I have limits.\nReflecting on this,\nI abide in the Absolute." },
      { id: "2.18", number: "2.18", speaker: "Janaka said:", text: "I am neither free nor bound.\nThe illusion of such things\nhas fallen into disbelief.\nThough I contain creation,\nit has no substance." },
      { id: "2.19", number: "2.19", speaker: "Janaka said:", text: "Having seen for certain\nthat this universe and body\nis without form or substance,\nI am revealed as Awareness alone.\nImagination has no place here." },
      { id: "2.20", number: "2.20", speaker: "Janaka said:", text: "The body exists only in imagination,\nas do heaven and hell,\nbondage, freedom, fear.\nAre these my concern?\nI, who am pure Awareness?" },
    ]
  },
  {
    id: 18,
    title: "Peace",
    verses: [
      { id: "18.1", number: "18.1", speaker: "Ashtavakra said:", text: "Praise That,\nwhich is Bliss itself,\nwhich is by nature stillness and light,\nand which by Its knowing\nreveals the world as a dream." },
      { id: "18.2", number: "18.2", speaker: "Ashtavakra said:", text: "One may enjoy the abundant pleasures of the world,\nbut will never be happy\nuntil giving them up." },
      { id: "18.3", number: "18.3", speaker: "Ashtavakra said:", text: "How can one whose innermost heart\nhas been scorched by the sun of sorrow\nthat comes from duty\nbe happy until the sweet rain\nof torrential stillness?" },
      { id: "18.4", number: "18.4", speaker: "Ashtavakra said:", text: "The universe is but a thought\nin Consciousness.\nIn Reality it is nothing.\nOne who sees the true nature\nof existence and non-existence\nnever ceases to exist." },
      { id: "18.5", number: "18.5", speaker: "Ashtavakra said:", text: "The Self—which is\nabsolute, effortless, timeless, immaculate—\nis without limits\nand at no distance from you.\nYou are forever It." },
      { id: "18.6", number: "18.6", speaker: "Ashtavakra said:", text: "For those whose vision becomes unclouded,\nillusion evaporates\nand the Self becomes known.\nAll sorrow is instantly dispelled." },
      { id: "18.7", number: "18.7", speaker: "Ashtavakra said:", text: "Seeing everything is imagination,\nknowing the Self as timelessly free,\nthe sage lives as a child." },
      { id: "18.8", number: "18.8", speaker: "Ashtavakra said:", text: "Knowing himself as Absolute,\nknowing existence and non-existence\nto be imagination only,\nwhat is there for the desireless one\nto learn, say or do?" },
      { id: "18.9", number: "18.9", speaker: "Ashtavakra said:", text: "Knowing for certain that all is Self,\nthe sage has no trace of thoughts\nsuch as \"I am this\" or \"I am not that.\"" },
      { id: "18.10", number: "18.10", speaker: "Ashtavakra said:", text: "The yogi who finds stillness\nis neither distracted nor focused.\nHe knows neither pleasure nor pain.\nIgnorance dispelled,\nhe is free of knowing." },
      { id: "18.11", number: "18.11", speaker: "Ashtavakra said:", text: "Heaven or poverty,\ngain or loss,\nsociety or solitude,\nto the yogi free of conditioning\nthere is no difference." },
      { id: "18.12", number: "18.12", speaker: "Ashtavakra said:", text: "Religious merit,\nsensory pleasure,\nworldly prosperity,\ndiscrimination between this and that—\nthese have no significance\nto the yogi free of opposites\nsuch as \"I do this\"\nand \"this I do not.\"" },
      { id: "18.13", number: "18.13", speaker: "Ashtavakra said:", text: "The yogi who is liberated while living\nhas no duties in this world,\nno attachments in his heart.\nHis life proceeds without him." },
      { id: "18.14", number: "18.14", speaker: "Ashtavakra said:", text: "For the great soul\nwho abides beyond desire,\nwhere is illusion?\nWhere is the universe?\nWhere is meditation on That?\nWhere even is liberation from them?" },
      { id: "18.15", number: "18.15", speaker: "Ashtavakra said:", text: "He who sees the world\nmay try to renounce it.\nBut what can the desireless one do?\nHe sees there is nothing to see." },
      { id: "18.16", number: "18.16", speaker: "Ashtavakra said:", text: "He who has seen the Supreme Brahma\nthinks, \"I am Brahma.\"\nBut he who has transcended all thought,\nwhat can he think?\nHe knows no other than Self." },
      { id: "18.17", number: "18.17", speaker: "Ashtavakra said:", text: "He achieves self-control\nwho sees his own distraction.\nBut the great soul is not distracted.\nHe has nothing to achieve.\nHe has nothing to do." },
      { id: "18.18", number: "18.18", speaker: "Ashtavakra said:", text: "The man of Knowledge\nmay live as an ordinary man,\nbut he is not.\nHe sees he is neither\nfocused nor distracted,\nand finds no fault with himself." },
      { id: "18.19", number: "18.19", speaker: "Ashtavakra said:", text: "He who is beyond existence and non-existence—\nwho is wise, satisfied, free of desire—\ndoes nothing,\nthough the world may see him in motion." },
      { id: "18.20", number: "18.20", speaker: "Ashtavakra said:", text: "The wise one\nis not troubled by action or inactivity.\nHe lives happily,\ndoing whatever gets done." },
      { id: "18.21", number: "18.21", speaker: "Ashtavakra said:", text: "Like a leaf in the wind\nthe liberated one\nis untethered from life—\ndesireless, independent, free." },
      { id: "18.22", number: "18.22", speaker: "Ashtavakra said:", text: "For one who has transcended the world\nthere is no joy or sorrow.\nWith a stilled mind,\nhe lives on with no body." },
      { id: "18.23", number: "18.23", speaker: "Ashtavakra said:", text: "One who knows Self,\nwhose mind is serene and spotless,\ndoes not desire to give up anything,\nnor does he miss what is not there." },
      { id: "18.24", number: "18.24", speaker: "Ashtavakra said:", text: "His mind being in a natural state\nof emptiness,\nthe wise one knows nothing\nof honor and dishonor.\nHe does what comes to be done." },
      { id: "18.25", number: "18.25", speaker: "Ashtavakra said:", text: "One who acts knowing\n\"This is done by the body, not by I, pure Self,\"\nindeed does nothing—\nno matter how much acting takes place." },
      { id: "18.26", number: "18.26", speaker: "Ashtavakra said:", text: "The liberated one\nacts without claiming to be acting,\nbut he is no fool.\nHe is blessed and happy\neven though in the world." },
      { id: "18.27", number: "18.27", speaker: "Ashtavakra said:", text: "Having had enough\nof the endless workings of the mind,\nthe wise one comes to rest.\nHe neither thinks, nor knows,\nnor hears, nor sees." },
      { id: "18.28", number: "18.28", speaker: "Ashtavakra said:", text: "Beyond stillness,\nbeyond distraction,\nthe great soul thinks nothing\nof liberation or bondage.\nHaving seen the universe is void—\neven though it seems to exist—\nhe is God." },
      { id: "18.29", number: "18.29", speaker: "Ashtavakra said:", text: "He who believes he is a person\nis constantly acting,\neven when the body is at rest.\nThe sage knows he is not a person,\nand therefore does nothing,\neven when the body is in motion." },
      { id: "18.30", number: "18.30", speaker: "Ashtavakra said:", text: "The mind of the liberated one\nis neither troubled nor pleased.\nIt is actionless, motionless, desireless\nand free of doubt." },
      { id: "18.31", number: "18.31", speaker: "Ashtavakra said:", text: "The liberated one\ndoes not exert effort\nto meditate or act.\nAction and meditation just happen." },
      { id: "18.32", number: "18.32", speaker: "Ashtavakra said:", text: "Hearing ultimate Truth,\nthe dull-witted man is bewildered.\nThe wise man hearing Truth\nretreats within and appears\ndull-witted." },
      { id: "18.33", number: "18.33", speaker: "Ashtavakra said:", text: "The ignorant practice\nmeditation and no-thought.\nThe wise,\nlike men in deep sleep,\ndo nothing." },
      { id: "18.34", number: "18.34", speaker: "Ashtavakra said:", text: "The ignorant man finds no peace\neither by effort or non-effort.\nThe wise man\nby Truth alone is stilled." },
      { id: "18.35", number: "18.35", speaker: "Ashtavakra said:", text: "Though they are by nature Self alone,\npure intelligence, love and perfection;\nthough they transcend the universe\nand are clearness itself,\nmen of the world will not see this\nthrough meditation and practices." },
      { id: "18.36", number: "18.36", speaker: "Ashtavakra said:", text: "The ignorant man\nwill never be liberated\nby his repetitious practices.\nBlessed is he who\nby simple understanding\nenters timeless freedom." },
      { id: "18.37", number: "18.37", speaker: "Ashtavakra said:", text: "Because he desires to know God,\nthe ignorant man can never become That.\nThe wise man is God\nbecause he is free of desire\nand knows nothing." },
      { id: "18.38", number: "18.38", speaker: "Ashtavakra said:", text: "Unable to stand steady\nand eager for salvation,\nthe ignorant perpetuate\nthe illusion of world.\nSeeing the world\nas the source of all misery,\nthe wise cut it off at the root." },
      { id: "18.39", number: "18.39", speaker: "Ashtavakra said:", text: "The fool thinks peace comes\nby controlling the mind.\nHe will never attain it.\nThe wise one knows Truth,\nand is stillness itself." },
      { id: "18.40", number: "18.40", speaker: "Ashtavakra said:", text: "For he who thinks knowledge\nis things and ideas\nhow can there be Self-knowledge?\nThe wise do not see separate things—\nonly the timeless Self." },
      { id: "18.41", number: "18.41", speaker: "Ashtavakra said:", text: "The fool tries to control the mind\nwith the mind—what folly!\nThe wise one delights in Self alone.\nThere is no mind to master." },
      { id: "18.42", number: "18.42", speaker: "Ashtavakra said:", text: "Some believe in existence;\nothers believe nothing exists.\nRare is the one who believes nothing\nand is never confused." },
      { id: "18.43", number: "18.43", speaker: "Ashtavakra said:", text: "Weak intellectuals may believe\nthe Self is One without other.\nBut being mired in illusion\nthey do not actually know Self,\nso live out their lives in misery." },
      { id: "18.44", number: "18.44", speaker: "Ashtavakra said:", text: "The mind of one seeking liberation\ndepends on things for perception.\nThe mind of the liberated one\nperceives no-thing\nand is free of desire." },
      { id: "18.45", number: "18.45", speaker: "Ashtavakra said:", text: "Timid men fear sensory experience\nmuch as they do tigers.\nThey seek refuge in caves\nand try to un-think the world." },
      { id: "18.46", number: "18.46", speaker: "Ashtavakra said:", text: "Sensory experiences are like elephants who,\nupon encountering a desireless man,\nsee him as a lion.\nThey immediately turn on their heels,\nor if unable to escape,\nstay on to flatter and serve him." },
      { id: "18.47", number: "18.47", speaker: "Ashtavakra said:", text: "A man with no doubts,\nwho knows only Self,\nhas no need of practice\nor liberation.\nSeeing, hearing, touching, smelling, eating—\nhe lives as he is, happily." },
      { id: "18.48", number: "18.48", speaker: "Ashtavakra said:", text: "One whose mind is emptied and unconflicted\nby the mere hearing of Truth\nsees nothing to do,\nnothing to avoid,\nnothing to warrant his indifference." },
      { id: "18.49", number: "18.49", speaker: "Ashtavakra said:", text: "The sage does whatever\nappears to be done\nwithout thinking of good or bad.\nHis actions are those of a child." },
      { id: "18.50", number: "18.50", speaker: "Ashtavakra said:", text: "Depending on nothing,\none finds happiness.\nDepending on nothing,\none attains the Supreme.\nDepending on nothing,\none passes through tranquility\nto One Self." },
      { id: "18.51", number: "18.51", speaker: "Ashtavakra said:", text: "When one realizes\nhe is neither the actor\nnor the one who watches,\nthe mind-storm is stilled." },
      { id: "18.52", number: "18.52", speaker: "Ashtavakra said:", text: "The actions of the sage,\nfree of pretence and motive,\nshine like clear light.\nNot so those of the deluded seeker\nwho affects a peaceful demeanor\nwhile remaining firmly attached." },
      { id: "18.53", number: "18.53", speaker: "Ashtavakra said:", text: "Unbounded, unfettered,\nuntethered from the projections of mind,\nthe wise are free to play and enjoy,\nor retire to mountain caves." },
      { id: "18.54", number: "18.54", speaker: "Ashtavakra said:", text: "Whether honoring a spiritual scholar,\na god, or holy shrine;\nwhether seeing a desirable woman,\na king, or beloved friend—\nthe heart of the sage\nis unmoved." },
      { id: "18.55", number: "18.55", speaker: "Ashtavakra said:", text: "Though his servants, sons,\nwives, daughters, grandchildren\nand all his relatives\nridicule and despise him,\nthe yogi is undismayed." },
      { id: "18.56", number: "18.56", speaker: "Ashtavakra said:", text: "Though pleased he is not pleasured;\nthough pained he does not suffer.\nThis wonderful state is understood\nonly by those like him." },
      { id: "18.57", number: "18.57", speaker: "Ashtavakra said:", text: "The belief in duty\ncreates a relative world\nfor its performance.\nThe wise one knows Himself\nto be formless, timeless,\nall-pervasive, immaculate,\nand thus transcends duty and world." },
      { id: "18.58", number: "18.58", speaker: "Ashtavakra said:", text: "Even doing nothing\nthe dull one is anxious and distracted.\nEven amidst great action\nthe wise one remains still." },
      { id: "18.59", number: "18.59", speaker: "Ashtavakra said:", text: "Even in practical life\nthe wise one remains happy.\nHappy to sit,\nhappy to sleep,\nhappy to move about,\nhappy to speak,\nhappy to eat..." },
      { id: "18.60", number: "18.60", speaker: "Ashtavakra said:", text: "Because he knows Self\nthe wise one is not disrupted by practical life.\nHe is deep and still, like a vast lake.\nHe is not like ordinary people.\nHis sorrows have vanished." },
      { id: "18.61", number: "18.61", speaker: "Ashtavakra said:", text: "For the deluded one,\neven rest is an activity.\nFor the wise,\neven action bears the fruit of stillness." },
      { id: "18.62", number: "18.62", speaker: "Ashtavakra said:", text: "The deluded one is often adverse\nto the things of his life.\nTo one with no thought for body,\nattachment and aversion have no meaning." },
      { id: "18.63", number: "18.63", speaker: "Ashtavakra said:", text: "The deluded mind is caught up\nin thinking and not thinking.\nThough the mind of the wise one\nmay think what thoughts come,\nhe is not aware of it." },
      { id: "18.64", number: "18.64", speaker: "Ashtavakra said:", text: "The sage sees nothing being done\neven when performed by his hands.\nLike a child he is pure\nand acts without reason." },
      { id: "18.65", number: "18.65", speaker: "Ashtavakra said:", text: "Blessed indeed is he who knows Self.\nThough seeing, hearing, touching, smelling, eating,\nhe never desires nor changes." },
      { id: "18.66", number: "18.66", speaker: "Ashtavakra said:", text: "For one who is void and changeless,\nwhere is the world and its imaginings?\nWhere is the end?\nWhere is the possibility of it?" },
      { id: "18.67", number: "18.67", speaker: "Ashtavakra said:", text: "Glorious indeed is he who,\nfree of desire,\nembodies Bliss itself.\nHe has become absorbed in Self." },
      { id: "18.68", number: "18.68", speaker: "Ashtavakra said:", text: "In short, the great soul\nwho has realized Truth\nis free of desire, enjoyment and liberation.\nIn all of space and time\nhe is attached to nothing." },
      { id: "18.69", number: "18.69", speaker: "Ashtavakra said:", text: "What remains for One\nwho is Consciousness itself,\nwho sees the non-existence\nof a phenomenal world created\nby the mere thought of a name?" },
      { id: "18.70", number: "18.70", speaker: "Ashtavakra said:", text: "Peace is natural for one\nwho knows for certain nothing exists,\nwho sees appearances are illusion,\nto whom the inexpressible is apparent." },
      { id: "18.71", number: "18.71", speaker: "Ashtavakra said:", text: "Rules of conduct, detachment,\nrenunciation, asceticism—\nwhat are these to one\nwho sees the unreality of things,\nwho is the Light of Awareness?" },
      { id: "18.72", number: "18.72", speaker: "Ashtavakra said:", text: "How can there be joy or sorrow,\nbondage or liberation,\nfor one who perceives non-existence\nand lights the infinite?" },
      { id: "18.73", number: "18.73", speaker: "Ashtavakra said:", text: "Until Self-realization,\nillusion prevails.\nThe sage lives without\nthoughts of \"I\" or \"mine.\"\nHis connection to illusion is severed." },
      { id: "18.74", number: "18.74", speaker: "Ashtavakra said:", text: "What is knowledge?\nWhat is the universe?\nWhat are thoughts like\n\"I am the body,\" or \"the body is mine\"?\nThe sage is imperishable and sorrowless.\nHe is Self alone." },
      { id: "18.75", number: "18.75", speaker: "Ashtavakra said:", text: "When a weak man gives up meditation\nhe falls prey to whims and desires." },
      { id: "18.76", number: "18.76", speaker: "Ashtavakra said:", text: "Even hearing Truth,\nthe man of dull intellect\nholds on to illusion.\nThrough effort and suppression\nhe may appear outwardly composed,\nbut inside he craves the world." },
      { id: "18.77", number: "18.77", speaker: "Ashtavakra said:", text: "Though others may see him working,\nthe sage does nothing.\nKnowledge has banished effort.\nHe finds no reason to do or say." },
      { id: "18.78", number: "18.78", speaker: "Ashtavakra said:", text: "The sage is fearless, unassailable.\nNo darkness, no light, nothing to lose.\nNothing." },
      { id: "18.79", number: "18.79", speaker: "Ashtavakra said:", text: "Patience, discrimination,\neven fearlessness—\nWhat use are these to the yogi?\nHis nature cannot be described.\nHe is not a person." },
      { id: "18.80", number: "18.80", speaker: "Ashtavakra said:", text: "No heaven, no hell,\nno liberation for the living.\nIn short, Consciousness is Void.\nWhat more can be said?" },
      { id: "18.81", number: "18.81", speaker: "Ashtavakra said:", text: "The sage neither yearns for fulfillment\nnor frets over non-attainment.\nHis mind is cool\nand brimming with sweetness." },
      { id: "18.82", number: "18.82", speaker: "Ashtavakra said:", text: "Detached from desire,\nthe sage neither praises peace\nnor blames the wicked.\nEqually content\nin happiness and misery,\nhe would not change a thing." },
      { id: "18.83", number: "18.83", speaker: "Ashtavakra said:", text: "The sage neither rejects the world\nnor desires Self.\nHe is free of joy and sorrow.\nHe does not live\nand cannot die." },
      { id: "18.84", number: "18.84", speaker: "Ashtavakra said:", text: "The wise one lives without hope.\nHe has no attachment to his children, wife or anyone.\nPleasure means nothing to him.\nHis life is glorious." },
      { id: "18.85", number: "18.85", speaker: "Ashtavakra said:", text: "The sage wanders about as he pleases\nand lives on whatever may come.\nContentment ever dwells in his heart.\nAnd when the sun sets,\nhe rests where he is." },
      { id: "18.86", number: "18.86", speaker: "Ashtavakra said:", text: "Rooted in Being,\nno thought of being born or reborn,\nthe great soul is indifferent\nto the death or birth of his body." },
      { id: "18.87", number: "18.87", speaker: "Ashtavakra said:", text: "The wise one stands alone,\ncaring for nothing,\nbereft of possessions.\nHe goes where he will,\nunhindered by opposites,\nhis doubts rent asunder.\nHe is truly blessed." },
      { id: "18.88", number: "18.88", speaker: "Ashtavakra said:", text: "The wise one has no sense of \"mine.\"\nTo him earth, stone and gold are the same.\nThe knots of his heart have unraveled.\nHe knows neither ignorance nor sorrow.\nHe is excellent in every way." },
      { id: "18.89", number: "18.89", speaker: "Ashtavakra said:", text: "The liberated soul\nhas no desire in his heart.\nHe is content and indifferent.\nHe has no equal." },
      { id: "18.90", number: "18.90", speaker: "Ashtavakra said:", text: "Only one free of desire\nknows nothing of knowing,\nsays nothing needs saying,\nsees nothing to see." },
      { id: "18.91", number: "18.91", speaker: "Ashtavakra said:", text: "He who is without desire excels,\nbe he beggar or king.\nHe no longer sees good or bad." },
      { id: "18.92", number: "18.92", speaker: "Ashtavakra said:", text: "What is lust or restraint,\nor the desire for Truth\nto the yogi who has reached life's goal,\nand who embodies virtue and sincerity?" },
      { id: "18.93", number: "18.93", speaker: "Ashtavakra said:", text: "The inner experience of one\nwho is free of desire and suffering,\nwho is content and reposes in Self—\nhow can it be described,\nand of whom?" },
      { id: "18.94", number: "18.94", speaker: "Ashtavakra said:", text: "The wise one's state never varies.\nSleeping soundly, he is not asleep.\nLying in reverie, he is not dreaming.\nEyes open, he is not wakeful." },
      { id: "18.95", number: "18.95", speaker: "Ashtavakra said:", text: "The man of Knowledge seems to think,\nbut has no thoughts.\nHe seems to have sense perceptions,\nbut does not experience.\nHe seems to have intelligence,\nbut is empty-minded.\nHe appears to be a person,\nbut is not." },
      { id: "18.96", number: "18.96", speaker: "Ashtavakra said:", text: "The man of Knowledge\nis neither happy nor miserable,\nneither detached nor attached,\nneither liberated nor seeking liberation.\nHe is neither this nor that." },
      { id: "18.97", number: "18.97", speaker: "Ashtavakra said:", text: "Even while distracted the blessed one is still.\nIn meditation, he does not meditate.\nIn ignorance, he remains clear.\nThough learned, he knows nothing." },
      { id: "18.98", number: "18.98", speaker: "Ashtavakra said:", text: "The liberated one,\nwho abides unconditionally in Self,\nwho is free of the concept of action and duty,\nwho is always and everywhere the same,\nis desireless.\nHe does not worry\nabout what he did or did not do." },
      { id: "18.99", number: "18.99", speaker: "Ashtavakra said:", text: "The wise one is neither pleased by praise,\nnor annoyed by blame.\nHe neither rejoices in life\nnor fears death." },
      { id: "18.100", number: "18.100", speaker: "Ashtavakra said:", text: "One of tranquil mind\nseeks neither crowds nor wilderness.\nHe is the same wherever he goes." },
    ]
  },
  {
    id: 19,
    title: "Repose in the Self",
    verses: [
      { id: "19.1", number: "19.1", speaker: "Janaka said:", text: "With the tongs of Truth\nI have plucked the thorn of thinking\nfrom the innermost cave\nof my heart." },
      { id: "19.2", number: "19.2", speaker: "Janaka said:", text: "Where is meditation, pleasure,\nprosperity or discrimination?\nWhere is duality?\nWhere even is Unity?\nI abide in the glory of Self." },
      { id: "19.3", number: "19.3", speaker: "Janaka said:", text: "Where is past and future,\nor even present?\nWhere is space, or even eternity?\nI abide in the glory of Self." },
      { id: "19.4", number: "19.4", speaker: "Janaka said:", text: "Where is Self?\nWhere is not-Self?\nWhere is good and evil, confusion and clarity?\nI abide in the glory of Self." },
      { id: "19.5", number: "19.5", speaker: "Janaka said:", text: "Where is sleeping, dreaming, waking,\nor even the fourth state?\nWhere is fear?\nI abide in the glory of Self." },
      { id: "19.6", number: "19.6", speaker: "Janaka said:", text: "Where is close or far,\nin or out,\ngross or subtle?\nI abide in the glory of Self." },
      { id: "19.7", number: "19.7", speaker: "Janaka said:", text: "Where is life and death?\nWhere is the world and worldly relations?\nWhere is distraction and stillness?\nI abide in the glory of Self." },
      { id: "19.8", number: "19.8", speaker: "Janaka said:", text: "There is no need to talk about\nthe three ends of life.\nTo talk of yoga is purposeless.\nEven talking about Truth is irrelevant.\nI rest in Self alone." },
    ]
  },
  {
    id: 20,
    title: "Liberation-in-Life",
    verses: [
      { id: "20.1", number: "20.1", speaker: "Janaka said:", text: "Where are the elements, the body,\nthe organs, the mind?\nWhere is the void?\nWhere is despair?\nMy nature is transparent clearness." },
      { id: "20.2", number: "20.2", speaker: "Janaka said:", text: "Where is scripture?\nWhere is Self-knowledge?\nWhere is no-mind?\nWhere is contentment and freedom from desire?\nI am empty of two-ness." },
      { id: "20.3", number: "20.3", speaker: "Janaka said:", text: "Where is Knowledge and ignorance?\nWhere is \"I\"?\nWhere is \"this\"?\nWhere is \"mine\"?\nWhere is bondage and liberation?\nSelf has no attributes." },
      { id: "20.4", number: "20.4", speaker: "Janaka said:", text: "Where is the unfolding of karma?\nWhere is liberation-in-life,\nor even liberation at death?\nThere is only One." },
      { id: "20.5", number: "20.5", speaker: "Janaka said:", text: "Where is the doer or enjoyer?\nWhere is the origin or end of thought?\nWhere is direct or reflected knowledge?\nThere is no person here." },
    ]
  }
];
